### ISSUE TITLE
Processing Hifi and ccs reads from one sample

### ISSUE THREAD

**Issue by priyambial123** [PacificBiosciences/pb-human-wgs-workflow-snakemake#110]
Hello
I have sequenced data from one  SMRT cell but the reads yield was low. We also did ultra-low input method and have ccs.read data for the same sample with better read yield. Now, I have hifi.read data with low yield and ccs.read data with better yield for the same sample.  Do you have any suggestions to use the information from both files. Can these files be processed together Please advice.

Thanks
Priya

**Comment by williamrowell** [comment]
This workflow is designed for WGS and not optimized for ultra-low input, and in general I wouldn't recommend mixing these datatypes as they have different downstream analysis requirements.

As described in the [App Note](https://www.pacb.com/wp-content/uploads/Application-Note-Considerations-for-Using-the-Low-and-Ultra-Low-DNA-Input-Workflows-for-Whole-Genome-Sequencing.pdf), ultra-low input data requires two preprocessing steps: adapter trimming and deduplication.  These steps would be required upstream of the workflow in this repo.  Ultra-low input data also requires modifications to the parameters for structural variant calling with PBSV, as described in the App Note.  These modified parameters can be added to [config.yaml line 30](https://github.com/PacificBiosciences/pb-human-wgs-workflow-snakemake/blob/main/config.yaml#L30).
