### ISSUE TITLE
Combining reads run by ultra-low protocol method and the regular PacBio protocol

### ISSUE THREAD

**Issue by priyambial123** [PacificBiosciences/pb-human-wgs-workflow-snakemake#115]
Hello,

I need some advice in running the jellyfish step in the workflow. When I combine the reads from 2 SMRT cells (by ultra-low protocol method and the regular PacBio protocol) , I face issues in the merge step.

This is from the logs file:

`Can't merge hash with different size (2147483648, 4294967296)`
Here the runs were different, one was run by the usual PacBio protocol (resulted in low reads yield) and other run was by ultra-low protocol method

Is this expected to occur, when the reads are combined. Has anyone faced this issue and is there a way to fix this?

Thanks

**Comment by williamrowell** [comment]
This error can happen when working with very low coverage data.  Given that you have just one sample and don't really need sample swap detection, the easiest fix is to disable k-mer counting/merging.  Place a `#` immediately before the `-` on [line 6](https://github.com/PacificBiosciences/pb-human-wgs-workflow-snakemake/blob/main/config.yaml#L6) and [line 13](https://github.com/PacificBiosciences/pb-human-wgs-workflow-snakemake/blob/main/config.yaml#L13] of [config.yaml](https://github.com/PacificBiosciences/pb-human-wgs-workflow-snakemake/blob/main/config.yaml).
