### ISSUE TITLE
Plan for TRGT

### ISSUE THREAD

**Issue by yfukasawa** [PacificBiosciences/pb-human-wgs-workflow-snakemake#121]
Hi @williamrowell,

Thank you for developing and maintaining an awesome pipeline!
I recently came to know a new tool [TRGT](https://github.com/pacificbiosciences/trgt), developed by PacBio team.

Any plan to integrate TRGT into this snakemake pipeline soon?

Yoshinori

**Comment by williamrowell** [comment]
Glad you're enjoying it.  I have some internal rules written for trgt, but I was waiting for the API to stabilize and the first bioconda release.  I'll try to add it in the next couple weeks.

**Comment by yfukasawa** [comment]
Thank you for your considerations. Looking forward to seeing the tool in the pipeline!
