### ISSUE TITLE
snakemake version incompatible with --max-threads=256

### ISSUE THREAD

**Issue by lauragails** [PacificBiosciences/pb-human-wgs-workflow-snakemake#126]
Hello - I followed the tutorial [here](https://github.com/PacificBiosciences/pb-human-wgs-workflow-snakemake/blob/main/Tutorial.md) and am now set to run the pipeline. Specifically related to this issue, I ran the following command to make the conda environment: 
```
mamba create -c conda-forge -c bioconda -n pb-human-wgs-111622 snakemake=6.15.3 lockfile=0.12.2 pysam=0.16.0.1 python=3

```

This worked fine! 

But when running `$DIR_EXECUTABLE/workflow/process_smrtcells.lsf.sh` I get the error: 
snakemake: error: unrecognized arguments: **--max-threads=256** 

This seems to be due to the snakemake version. Later versions of snakemake have this argument, as `snakemake -h` in the created environment doesn't have that argument. The latest version of snakemake does, though [link](https://snakemake.readthedocs.io/en/stable/executing/cli.html#all-options). 

I'm installing a later version now, but thought I'd also fill out a ticket (especially since there might also be issues downstream). 

Thank you (and thank you for your help at ASHG)!

**Comment by lauragails** [comment]
(it looks like this flag is present in snakemake 6.15.5 - trying that now!)

**Comment by williamrowell** [comment]
Is it possible that there's a snakemake outside of the conda env and there's a path issue?  What does `which -a snakemake` look like?

**Comment by lauragails** [comment]
which -a snakemake
/sc/arion/work/sloofl01/pb-human-wgs/envs/pb-human-wgs-debug/bin/snakemake
/hpc/packages/minerva-centos7/py_packages/3.7/bin/snakemake

Good point about the outside - that version in py_packages is the old
version that doesn't have a manual.

What I think is happening is that I have py_packages and python loaded on
our hpc when I'm creating the environment, and something is getting
confused. I'll try to remake the environment again without loading our hpc
modules, and maybe it will work.

Likewise, let me know if you have other suggestions!

**Comment by williamrowell** [comment]
It's weird because your env snakemake is higher priority in the path than the module snakemake.  I've seen this sort of thing before, though.  Somewhere, the path is getting scrambled. Maybe the module is getting loaded a second time and ending up higher in the priority. If you can avoid loading hpc modules, that's definitely the way to go about it.

**Comment by lauragails** [comment]
it's working!! module unloading `python` and `py_packages` did the trick.  

So far, all of the files are entering the dictionary etc. and relevant packages are being downloaded, jobs are being created etc. Will let you know if other issues come up. 

Thank you again!

**Comment by williamrowell** [comment]
No problem, glad we found the solution.
