### ISSUE TITLE
lockfile: command not found

### ISSUE THREAD

**Issue by lauragails** [PacificBiosciences/pb-human-wgs-workflow-snakemake#134]
RE line 12 in process sample local: 

`lockfile -r 0 ${LOCKFILE} || exit 1`

I am sure that my environment is loading correctly, and I can see that `./lib/python3.6/site-packages/lockfile` was installed in the appropriate place in my environment. 

This is how I created the environment I'm using: 
`mamba create -c conda-forge -c bioconda -n pb-human-wgs-debug2 snakemake=6.15.5 lockfile=0.12.2 pysam=0.16.0.1 python=3 `

However, this line is failing with the error: `line 12: lockfile: command not found`

A sample command that I used to run step 2 is: `./workflow/process_sample.local.sh sample_ID `

How can I find the command and/or make the python software work in the bash context (if this is the right package)?  

Thank you!

**Comment by williamrowell** [comment]
Yeah, lockfile isn't working as expected here.  I'll look into it more after Thanksgiving, but the good news is that in the meantime, you can comment `line 12` out (and the similar line in `process_cohort.local.sh`).  This is meant to prevent the user from running the same command twice on the same sample at the same time.  If you're careful in the meantime, it shouldn't be a problem.

**Comment by lauragails** [comment]
Got it - yeah I submit with loops so that's not an issue. Will do!  

(Happy Thanksgiving)
