### ISSUE TITLE
**Error in rule bgzip_vcf:**

### ISSUE THREAD

**Issue by lauragails** [PacificBiosciences/pb-human-wgs-workflow-snakemake#148]
Hello all, 
I am running `workflow/process_sample.local.sh` and am getting the following error. Do you know what it may be? I still have 14TB in my drive so I don't think it's a space issue. Thank you! 

```
Activating conda environment: /sc/arion/projects/buxbaj01a/sloofl01/pac_bio/results/pacbio_wgs/121422/.snakemake/conda/5ff67c95a92013e755a25aa039b66191
[Sun Jan  1 20:50:34 2023]
**Error in rule bgzip_vcf:**
    jobid: 40
    output: samples/sample_name/pbsv/sample_name.GRCh38.chrom_vcfs/sample_name.GRCh38.chr13.pbsv.vcf.gz
    log: samples/sample_name/logs/bgzip/pbsv/sample_name.GRCh38.chrom_vcfs/sample_name.GRCh38.chr13.pbsv.log (check log file(s) for error message)
    conda-env: /sc/arion/projects/buxbaj01a/sloofl01/pac_bio/results/pacbio_wgs/121422/.snakemake/conda/d50d78097d235df7b794ad93c4e7d7da
    shell:
        (bgzip --threads 2 samples/sample_name/pbsv/sample_name.GRCh38.chrom_vcfs/sample_name.GRCh38.chr13.pbsv.vcf) > samples/sample_name/logs/bgzip/pbsv/sample_name.GRCh38.chrom_vcfs/sample_name.GRCh38.chr13.pbsv.log 2>&1
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```

**Comment by williamrowell** [comment]
Is there anything in `samples/sample_name/logs/bgzip/pbsv/sample_name.GRCh38.chrom_vcfs/sample_name.GRCh38.chr13.pbsv.log`?

**Comment by lauragails** [comment]
Yes
```
bgzip: invalid option -- '-'
bgzip: invalid option -- 't'

Usage:   bgzip [options] [file] ...

Options: -c      write on standard output, keep original files unchanged
         -d      decompress
         -f      overwrite files without asking
         -b INT  decompress at virtual file pointer INT
         -s INT  decompress INT bytes in the uncompressed file
         -h      give this help
```

**Comment by williamrowell** [comment]
I think it's running the wrong `bgzip`.  Maybe there's another in your path that somehow has precedent?

Try:
```bash
which -a bgzip
```

**Comment by lauragails** [comment]
aaah I bet it's that same module issue that we had with python: 

which -a bgzip
/hpc/packages/minerva-common/tabix/0.2.6/tabix-0.2.6/bgzip
/hpc/packages/minerva-centos7/htslib/1.9/bin/bgzip 

The top one is the one that is chosen. Should one have been installed in the custom environment?

**Comment by williamrowell** [comment]
Yeah, it should be using the `bgzip` in `/sc/arion/projects/buxbaj01a/sloofl01/pac_bio/results/pacbio_wgs/121422/.snakemake/conda/5ff67c95a92013e755a25aa039b66191`.  Something in your environment is loading those hpc packages modules into your path _after_ the conda environment has been activated.

**Comment by lauragails** [comment]
Got it - I sent an email to our hpc admins to see how to override this. Thank you again for your help, and happy new year!

**Comment by williamrowell** [comment]
No problem.  Hope it's an easy fix.  Happy new year!
