### ISSUE TITLE
Issue in running last_align rule

### ISSUE THREAD

**Issue by priyambial123** [PacificBiosciences/pb-human-wgs-workflow-snakemake#167]
Hello,

I have been facing issues with conda libraries. So, I have installed micromamba and started using using it. For the PacBio workflow. I kept the all the existing rule scripts and directories and updated only the environment using the command:

`mamba create -c conda-forge -c bioconda -n pb-human-wgs snakemake=6.15.3 tabulate=0.8.10 pysam=0.16.0.1 python=3`

I faced no issue running the first step in the workflow (process_smrtcells.smk). But, last few steps in second step (process_sample.smk) didn't get completed. It stops in the last_align step (tandem genotyping). Log file shows bus error. Please find the attached log files. Is this a memory issue or bug.  

[log.txt](https://github.com/PacificBiosciences/pb-human-wgs-workflow-snakemake/files/11246484/log.txt)
[benchmark.log](https://github.com/PacificBiosciences/pb-human-wgs-workflow-snakemake/files/11246485/benchmark.log)

Thank you

Priya

**Comment by williamrowell** [comment]
It's hard to tell based on the log, but given that we haven't been having any trouble with this rule for a wide variety of samples, I think it's more likely to be a memory issue than a bug.

Now that we have an internal tool to genotype tandem repeats ([TRGT](http://github.com/pacificbiosciences/trgt)), we'll deprecate tandem-genotypes in future releases.  I'd recommend disabling it by commenting out line 15 in [`config.yaml`](https://github.com/PacificBiosciences/pb-human-wgs-workflow-snakemake/blob/306b2e79ce11c8736e58d0740d572bf836762559/config.yaml#L15):

```yaml
sample_targets:
  - pbsv_vcf  # req: alignment in config['smrtcells_targets']
  - deepvariant  # req: alignment in config['smrtcells_targets']
  - whatshap  # req: deepvariant
  - coverage  # req: whatshap
  - kmers  # req: kmers in config['smrtcells_targets']
  - assembly
  #- tandem-genotypes  # req: whatshap
  - trgt  # req: whatshap
  - 5mc_cpg_pileup # req: whatshap; also requires uBAM input with basemods
```

This should allow you to move past this error without having to troubleshoot resource requirements.

**Comment by priyambial123** [comment]
Thank you, it worked
