### ISSUE TITLE
Error running Glnexus 

### ISSUE THREAD

**Issue by priyambial123** [PacificBiosciences/pb-human-wgs-workflow-snakemake#169]
Hello

I had no problem running the process_cohort.smk (last step in pipeline). Recently, I could not run the cohort_glnexus file. It stops with error:

```
Error in rule glnexus:
    jobid: 90
    output: cohorts/0009/glnexus/0009.GRCh38.deepvariant.glnexus.bcf, cohorts/0009/glnexus/0009.GRCh38.GLnexus.DB
    log: cohorts/0009/logs/glnexus/0009.GRCh38.log (check log file(s) for error message)
    shell:

        (rm -rf cohorts/0009/glnexus/0009.GRCh38.GLnexus.DB &&         glnexus_cli --threads 24 --mem-gbytes 192             --dir cohorts/0009/glnexus/0009.GRCh38.GLnexus.DB             --config DeepVariant_unfiltered samples/0009-004/deepvariant/0009-004.GRCh38.deepvariant.g.vcf.gz samples/0009-007/deepvariant/0009-007.GRCh38.deepvariant.g.vcf.gz samples/0009-010/deepvariant/0009-010.GRCh38.deepvariant.g.vcf.gz > cohorts/0009/glnexus/0009.GRCh38.deepvariant.glnexus.bcf) 2> cohorts/0009/logs/glnexus/0009.GRCh38.log

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job glnexus since they might be corrupted:
cohorts/0009/glnexus/0009.GRCh38.deepvariant.glnexus.bcf
Shutting down, this might take some time.
```

I looked into the log file :
`/usr/bin/bash: line 1: glnexus_cli: command not found`

I downloaded the resources folder again and ran the process_cohort.smk again. But, I still get the same error. I also checked the rules files (cohort_glnexus.smk) and it was similar to the files in the GitHub. Is there any file should I check in the resources folder.

Thank you

**Comment by juniper-lake** [comment]
If the log file only contains the `command not found` error, then I don't think it's an issue with your resources folder. It is an issue with calling the `glnexus_cli` command. This job runs using a [singularity/docker container](https://github.com/PacificBiosciences/pb-human-wgs-workflow-snakemake/blob/d21477b5c7b315627fc962b1f48964e9081ea5db/rules/cohort_glnexus.smk#LL15C5-L15C5) that references a GLNEXUS_VERSION variable in the config file. 

File `rules/cohort_glnexus.smk`:
`container: f"docker://ghcr.io/dnanexus-rnd/glnexus:{config['GLNEXUS_VERSION']}"`
File `config.yaml`:
`GLNEXUS_VERSION: 'v1.4.1'`

If either of these lines are missing OR if the snakemake arguments allowing integration with singularity were accidentally disabled in the snakemake profiles (for example, [these lines in the slurm profile](https://github.com/PacificBiosciences/pb-human-wgs-workflow-snakemake/blob/d21477b5c7b315627fc962b1f48964e9081ea5db/profiles/slurm/config.yaml#L12)), then the docker won't be loaded and the commands won't be available. 

Please see the [snakemake documentation](https://snakemake.readthedocs.io/en/v5.7.3/snakefiles/deployment.html#running-jobs-in-containers) for more information about running jobs in containers:

**Comment by priyambial123** [comment]
Thank you for pointing out the singularity integration. 

I added a line to fix the issue:

`--use-singularity` in the below snakemake command and it is running now:

`snakemake --rerun-incomplete --reason --config "cohort='$COHORT'" --nolock --local-cores 4 --use-singularity --jobs 500 --max-jobs-per-second 1 --use-conda --conda-frontend mamba --cluster-config workflow/profiles/slurm/config.yaml --snakefile workflow/process_cohort.smk`

Thank you :-)
