### ISSUE TITLE
TRGT failing 

### ISSUE THREAD

**Issue by looxon93** [PacificBiosciences/pb-human-wgs-workflow-snakemake#171]
Hello, 

I was able to get process_sample workflow to finish up to 98%. Only thing failing is, TRGT with error: 

> Error in rule trgt_genotype:
    jobid: 263
    input: reference/human_GRCh38_no_alt_analysis_set.fasta, samples/HG002/whatshap/HG002.GRCh38.deepvariant.haplotagged.bam, samples/HG002/whatshap/HG002.GRCh38.deepvariant.haplotagged.bam.bai, reference/human_GRCh38_no_alt_analysis_set.trgt.bed
    output: samples/HG002/trgt/HG002.GRCh38.trgt.vcf.gz, samples/HG002/trgt/HG002.GRCh38.trgt.spanning.bam
    log: samples/HG002/logs/trgt/genotype.log (check log file(s) for error details)
    conda-env: .snakemake/conda/2ceea3b17f91263a9fdfdb0f3aa32ff5_
    shell:
        (trgt --threads 16             --genome reference/human_GRCh38_no_alt_analysis_set.fasta             --repeats reference/human_GRCh38_no_alt_analysis_set.trgt.bed             --reads samples/HG002/whatshap/HG002.GRCh38.deepvariant.haplotagged.bam             --output-prefix samples/HG002/trgt/HG002.GRCh38.trgt) > samples/HG002/logs/trgt/genotype.log 2>&1
(one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
cluster_jobid: Submitted batch job 83503

> Error executing rule trgt_genotype on cluster (jobid: 263, external: Submitted batch job 83503, jobscript: .snakemake/tmp._ozzfjxu/snakejob.trgt_genotype.263.sh). For error details see the cluster log and the log files of the involved rule(s).
> Cleanup job metadata.

I printed out the error from TRGT and got: 
`thread 'main' panicked at 'assertion failed: name_and_value.len() == 2', src/locus.rs:65:5
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace`

Can someone help, how this happened?

**Comment by looxon93** [comment]
I fixed the issue with updating reference/human_GRCh38_no_alt_analysis_set.trgt.bed with repeat catalog from TRGT website: https://github.com/PacificBiosciences/trgt/blob/main/repeats/repeat_catalog.hg38.bed.

**Comment by juniper-lake** [comment]
Good to hear you were able to solve the issue. I will make a note that the TRGT error messages should be more helpful.
