### ISSUE TITLE
trgt de novo

### ISSUE THREAD

**Issue by lauragails** [PacificBiosciences/pb-human-wgs-workflow-snakemake#172]
Hello! Is there any plan to put trgt de novo in the pipeline? 

I only have 1 trio so it's easy to run as a stand-alone, but was curious for the future. 

Thank you, 
Laura

**Comment by williamrowell** [comment]
This workflow is no longer under active development.  All future development will be under the [PacificBiosciences/HiFi-human-WGS-WDL](https://github.com/PacificBiosciences/HiFi-human-WGS-WDL) workflow.  We haven't yet added TRGTdn, but may in the future.

**Comment by lauragails** [comment]
Got it, thank you Billy!

**Comment by lauragails** [comment]
(Is there any benefit to running the new pipeline for runs from ~1Y ago?)

**Comment by williamrowell** [comment]
It's really up to you.  The largest gains are in the additions of newer tools like Paraphase (typing a set of genes in segmental duplications) and HiFiCNV (depth-based CNV detection).  We've also replaced WhatsHap with an internally developed tool, HiPhase, that can phase both SVs and small variants (and STRs, to be implemented soon in the WDL workflow).  There are a lot of version updates for other tools as well.
_De novo_ assembly was removed to a separate workflow that will be public soon, and nothing changed for tertiary analysis.

You can find a full list of outputs [here](https://github.com/PacificBiosciences/HiFi-human-WGS-WDL?tab=readme-ov-file#workflow-outputs).
