### ISSUE TITLE
Simplify sample_deepvariant.smk?

### ISSUE THREAD

**Issue by Luobiny** [PacificBiosciences/pb-human-wgs-workflow-snakemake#22]
I am wondering if you guys thought about using /opt/deepvariant/bin/run_deepvariant to make sample_deepvariant.smk simpler?

**Comment by williamrowell** [comment]
`run_deepvariant` is definitely less complex, but it doesn't use resources as efficiently, especially if you want to use a GPU for the `call_variants` step.

1) `make_examples` is single threaded, but can be sharded.  Uses about 4-8Gb per thread.
2) `call_variants` can either run on all threads on a node, or on a single GPU.
3) `postprocess_variants` is single threaded, but uses about 24Gb mem.

`run_deepvariant` ties up all available threads for step 1, either 1 GPU or all available CPU threads for step 2, and 1 thread for step 3.  Running this in the cloud on a single node is reasonably cheap, but on our internal HPC, this is a bad use of resources.  We'd either tie up one of our higher thread CPU nodes for ~6h/job or one of our GPU nodes for ~2-3h/job (and our GPU nodes have 4x cards, of which DeepVariant only utilizes 1 at a time).

Running the three tasks independently allows for better use of resources on diverse HPCs.

**Comment by Luobiny** [comment]
That makes perfect sense, thank you!
