### ISSUE TITLE
Materials in the resources and references folder in the snakemake workflow

### ISSUE THREAD

**Issue by priyambial123** [PacificBiosciences/pb-human-wgs-workflow-snakemake#52]
Hello

I am following the instructions to implement the snakemake workflow from the given link: https://github.com/PacificBiosciences/pb-human-wgs-workflow-snakemake/blob/main/Tutorial.md. It is mentioned in the link that "to access the materials in the resources and references folder, to please contact one of the repository contributors or, if applicable, your PacBio representative to request these materials" (under the heading Prepare Workspace in the link). Please help to access the materials in the reference and resources folder to run the workflow

Thanks
Priya

**Comment by williamrowell** [comment]
I'm updating the resources and we'll add public links to the resources in `Tutorial.md` as soon as they're available.  In the meantime, email me at wrowell@pacificbiosciences.com and I'll get you access.
