### ISSUE TITLE
The order of parents in cohort.yaml in Tutorial.md is switched. 

### ISSUE THREAD

**Issue by Luobiny** [PacificBiosciences/pb-human-wgs-workflow-snakemake#84]
It seems the first entry should be mom and the second entry should be dad. Maybe it's less error-prone and less confusing to make 'parents' a dictionary of a mom entry and a dad entry instead of a list?

**Comment by williamrowell** [comment]
We'll fix the example in [example_cohort.yaml](https://github.com/PacificBiosciences/pb-human-wgs-workflow-snakemake/blob/main/example_cohort.yaml) in an upcoming PR. I don't want to implement a dictionary, as it would break backwards compatability.
