### ISSUE TITLE
Using resources --constraint=avx512 is not portable

### ISSUE THREAD

**Issue by holtgrewe** [PacificBiosciences/pb-human-wgs-workflow-snakemake#89]
When using deepvariant with CPU only it is not portable to hard-code `extra = '--contraint=avx512'` into the snakemake files.

```
# grep -R constraint= workflow/rules/
Binary file workflow/rules/.sample_deepvariant.smk.swp matches
workflow/rules/sample_deepvariant.smk:        extra = '--constraint=avx512'
workflow/rules/sample_deepvariant.smk:        extra = '--constraint=avx512'
workflow/rules/sample_deepvariant.smk:        extra = '--constraint=avx512'
workflow/rules/sample_deepvariant.smk:        extra = '--constraint=avx512'
```

Maybe this could be made configurable?

**Comment by holtgrewe** [comment]
The same is true for

```
    resources:
        partition = 'ml',
        extra = '--gpus=1'
```

**Comment by holtgrewe** [comment]
Also, this seems wrong

```
deepvariant_threads = 1000 if cpu_only else 8
```

As this is forwarded to sbatch... who has a node with 1000 hardware threads?

**Comment by williamrowell** [comment]
> When using deepvariant with CPU only it is not portable to hard-code `extra = '--contraint=avx512'` into the snakemake files.
> 
> ```
> # grep -R constraint= workflow/rules/
> Binary file workflow/rules/.sample_deepvariant.smk.swp matches
> workflow/rules/sample_deepvariant.smk:        extra = '--constraint=avx512'
> workflow/rules/sample_deepvariant.smk:        extra = '--constraint=avx512'
> workflow/rules/sample_deepvariant.smk:        extra = '--constraint=avx512'
> workflow/rules/sample_deepvariant.smk:        extra = '--constraint=avx512'
> ```
> 
> Maybe this could be made configurable?

We can break this out into the config.yaml.  The important thing here is that these jobs need to run on nodes with _at least_ avx2 instructions.

**Comment by juniper-lake** [comment]
> Also, this seems wrong
> 
> ```
> deepvariant_threads = 1000 if cpu_only else 8
> ```
> 
> As this is forwarded to sbatch... who has a node with 1000 hardware threads?

The snakemake CLI argument `--cores/--jobs` sets the maximum number of CPU cores and therefore overrides rule-specific designations of `threads`. The default for this setting is "all available CPU cores". 

At most, the job is going to use all available CPUs on its node, which is the purpose of setting this parameter arbitrarily high. The CPU version of this step has a tendency to clobber other jobs in resource usage, so we want to make sure snakemake doesn't let other jobs start at the same time.

There is likely a better way to achieve this goal "i.e. when in CPU-only mode, don't let other jobs start at the same time as this DeepVariant step" and we are always open to suggestions.
