### ISSUE TITLE
Memory is not properly provided for cluster execution

### ISSUE THREAD

**Issue by holtgrewe** [PacificBiosciences/pb-human-wgs-workflow-snakemake#90]
Our Slurm cluster enforces memory usage with cgroups. I added `--mem=32G` as a default to the snakemake profile. This is of course not good enough as it is too high for certain steps and too low for the assembly. If I increase it for assembly then the number of jobs running in parallel is too low.

The resolution would be to set proper memory resources for all rules.

**Comment by williamrowell** [comment]
Try setting `--mem-per-cpu=8G` as your default instead.  Our thread requests were designed with this assumption in mind.

**Comment by holtgrewe** [comment]
Thanks for the hint. Alas, I don't have nodes that have `48*8=384` GB of free RAM. I'll try using 32 threads for hifiasm for now...
